"""empty message

Revision ID: 1edb3d4985ce
Revises: 
Create Date: 2023-04-09 20:38:05.159562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1edb3d4985ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cache',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('validCode', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('pwd', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Integer(), nullable=True),
    sa.Column('head', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('cache')
    # ### end Alembic commands ###
