"""empty message

Revision ID: 252c3f05256a
Revises: c59f23a22172
Create Date: 2023-04-20 21:07:48.731645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '252c3f05256a'
down_revision = 'c59f23a22172'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('picture',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('fileName', sa.String(length=255), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('state', sa.Integer(), nullable=True),
    sa.Column('origin_path', sa.String(length=255), nullable=False),
    sa.Column('target_path', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('picture')
    # ### end Alembic commands ###
