"""empty message

Revision ID: 6168d78143a7
Revises: 
Create Date: 2023-03-01 20:21:46.967507

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6168d78143a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'pwd',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'role',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('user', 'pwd',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
